=== BarcelonaMedia-ViL/uima-development/code/SolrConsumer/src/main/resources/solrConsumerMapping.xsd
<?xml version="1.0"?>

<!--
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.    
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   elementFormDefault="qualified">

	<xs:element name="features">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="feature" minOccurs="0"
					maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="separator" type="xs:string"></xs:attribute>
			<xs:attribute name="coveredText" type="xs:boolean"></xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="feature">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="annotation" maxOccurs="1" minOccurs="0"></xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="annotations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="annotation" minOccurs="1"
					maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="separator" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="annotation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="features" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" />
			<xs:attribute name="sofa" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="field">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="annotations" minOccurs="1"
					maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="fields">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== BarcelonaMedia-ViL/uima-development/code/SolrConsumer/resources/mappingFiles/solrTabbed.xml
<?xml version="1.0" encoding="UTF-8"?>

<fields xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../src/main/resources/solrConsumerMapping.xsd">

    <field name="lemmas">
        <annotations>
            <annotation type="de.julielab.jules.types.Token">
                <features coveredText="true" separator="\t">
                    <feature name="lemma">
                        <annotation type="de.julielab.jules.types.Lemma">
                            <features>
                                <feature name="value"/>
                            </features>
                        </annotation>
                    </feature>
                    <feature name="posTag">
                        <annotation type="de.julielab.jules.types.POSTag">
                            <features>
                                <feature name="value"/>
                            </features>
                        </annotation>
                    </feature>
                </features>
            </annotation>
        </annotations>
    </field>
</fields>

=== BarcelonaMedia-ViL/uima-development/code/SolrConsumer/resources/mappingFiles/solrPaper.xml
<?xml version="1.0" encoding="UTF-8"?>

<fields xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../src/main/resources/solrConsumerMapping.xsd">

    <field name="Content">
        <annotations separator=" ">
            <annotation type="de.julielab.jules.types.Token">
                <features coveredText="true" separator='#'>
                    <feature name="posTag">
                        <annotation type="de.julielab.jules.types.POSTag">
                            <features>
                                <feature name="value"/>
                            </features>
                        </annotation>
                    </feature>
                </features>
            </annotation>
        </annotations>
    </field>
    <field name="payload">
        <annotations separator=" ">
            <annotation type="de.julielab.jules.types.Token">
                <features coveredText="true" separator='|'>
                    <feature name="posTag">
                        <annotation type="de.julielab.jules.types.POSTag">
                            <features>
                                <feature name="value"/>
                            </features>
                        </annotation>
                    </feature>
                </features>
            </annotation>
        </annotations>
    </field>    
</fields>

=== BarcelonaMedia-ViL/uima-development/code/SolrConsumer/resources/mappingFiles/solrExample.xml
<?xml version="1.0" encoding="UTF-8"?>

<fields xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../src/main/resources/solrConsumerMapping.xsd">

    <field name="texto">
        <annotations separator=" ">
            <annotation type="de.julielab.jules.types.Token">
                <features coveredText="true" separator=" "/>
            </annotation>
        </annotations>
    </field>
    <field name="lemmas">
        <annotations separator=" ">
            <annotation type="de.julielab.jules.types.Token">
                <features coveredText="false" separator="|">
                    <feature name="lemma">
                        <annotation type="de.julielab.jules.types.Lemma">
                            <features>
                                <feature name="value"/>
                            </features>
                        </annotation>
                    </feature>
                    <feature name="posTag">
                        <annotation type="de.julielab.jules.types.POSTag">
                            <features>
                                <feature name="value"/>
                            </features>
                        </annotation>
                    </feature>
                </features>
            </annotation>
        </annotations>
    </field>
    <field name="entity">
        <annotations separator=" ">
            <annotation type="de.julielab.jules.types.EntityMention">
                <features coveredText="true" separator="|">
                    <feature name="specificType"/>
                </features>
            </annotation>
        </annotations>
    </field>
</fields>
